#!/bin/bash

set -euo pipefail

profile="${AWS_PROFILE:=default}"

for var in "$@"
do
  case "$var" in
    --profile)
      profile="$2"
      ;;
    --help)
      echo "Usage:
    --profile        : Your AWS CLI profile, ie 'default'
      "
      exit 0
      ;;
  esac
  shift
done

echo "Getting session token..."
echo "Please enter your MFA code:"
read -r mfa
echo

user=$(aws iam get-user --query 'User.Arn' --output text --profile "$profile")
serial=$(echo "$user" | sed 's/:user/:mfa/')

response=$(aws sts get-session-token \
    --serial-number "$serial" \
    --duration-seconds 129600 \
    --token-code "$mfa" \
    --output json \
    --profile "$profile"
)

aws configure set profile.mfa.aws_access_key_id $(jq -r .Credentials.AccessKeyId <<< "$response")
aws configure set profile.mfa.aws_secret_access_key $(jq -r .Credentials.SecretAccessKey <<< "$response")
aws configure set profile.mfa.aws_session_token $(jq -r .Credentials.SessionToken <<< "$response")

