#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"
assets="$(cd "$(dirname "$0")" && pwd)/../assets"

title "AWS"

# dependencies
brew install gopass &>/dev/null
mkdir -p ~/.landtech

gopass sync &>/dev/null

echo_install "accounts.json configuration"
if json=$(gopass "${GOPASS_LANDTECH_STORE}"aws/accounts.jso1n &>/dev/null); then
    jq . <<<"$json" >~/.landtech/accounts.json
    print_in_green "${bold}✓ done!${normal}\n"
else
    print_in_red "${bold}✗ error!!!${normal} is your gopass set up? Try running 'gopass show aws/accounts.json'\n"
fi

for account in $(jq -r 'keys[]' <~/.landtech/accounts.json); do
    echo_install "aws cli profile: $account"
    aws configure set "$account".region eu-west-1
    aws configure set "$account".output json
    print_in_green "${bold}✓ done!${normal}\n"
done

echo_install "aliases"
mkdir -p "$HOME"/.aws/cli
cp -f "$assets"/aws-alias "$HOME"/.aws/cli/alias
print_in_green "${bold}✓ done!${normal}\n"

echo_install "aws-assume-role script"
rm -Rf ~/.bin/aws-assume-role
cp -f "$assets"/aws-assume-role ~/.bin
print_in_green "${bold}✓ done!${normal}\n"

echo_install "aws-get-session-token script"
rm -Rf ~/.bin/aws-get-session-token
cp -f "$assets"/aws-get-session-token ~/.bin
print_in_green "${bold}✓ done!${normal}\n"
