#!/usr/bin/env bash
set -e
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"
assets="$(cd "$(dirname "$0")" && pwd)/../assets"

title "AWS"

echo_install "aws cli profile: default"
aws configure set profile.default.region eu-west-1
aws configure set profile.default.output json
print_in_green "${bold}✓ done!${normal}\n"

echo_install "aliases"
mkdir -p "$HOME"/.aws/cli
cp -f "$assets"/aws-alias "$HOME"/.aws/cli/alias
print_in_green "${bold}✓ done!${normal}\n"

echo_install "aws-assume-role script"
rm -Rf ~/.bin/aws-assume-role
cp -f "$assets"/aws-assume-role ~/.bin
print_in_green "${bold}✓ done!${normal}\n"

echo_install "aws-get-session-token script"
rm -Rf ~/.bin/aws-get-session-token
cp -f "$assets"/aws-get-session-token ~/.bin
print_in_green "${bold}✓ done!${normal}\n"
