#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"
assets="$(cd "$(dirname "$0")" && pwd)/../assets"

title "AWS"

echo_install "accounts.json configuration"
mkdir -p ~/.landtech
gopass sync > /dev/null
gopass "${GOPASS_LANDTECH_STORE}"aws/accounts.json | jq . > ~/.landtech/accounts.json
print_in_green "${bold}✓ done!${normal}\n"

for account in $(jq -r 'keys[]' < ~/.landtech/accounts.json); do
    echo_install "aws cli profile: $account"
    aws configure set "$account".region eu-west-1
    aws configure set "$account".output json
    print_in_green "${bold}✓ done!${normal}\n"
done

echo_install "aws-assume-role script"
rm -Rf ~/.bin/aws-assume-role
cp --force "$assets"/aws-assume-role ~/.bin
print_in_green "${bold}✓ done!${normal}\n"

echo_install "aws-get-session-token script"
rm -Rf ~/.bin/aws-get-session-token
cp --force "$assets"/aws-get-session-token ~/.bin
print_in_green "${bold}✓ done!${normal}\n"
