#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"
assets="$(cd "$(dirname "$0")" && pwd)/../assets"

title "Kubernetes Mods"

echo_install "k8-install-cluster-user script"
rm -Rf ~/.bin/k8-install-cluster-user
cp --force "$assets"/k8-install-cluster-user ~/.bin
print_in_green "${bold}✓ done!${normal}\n"
