#!/usr/bin/env bash
source "$(pwd)/pretty-print"

if ! [ -x "$(command -v brew)" ]; then
    print_error "Docker is required, it should be included in the 'specs'
    return 1
fi

docker run -e GOOS=darwin -e GOARCH=amd64 -v ~/usr/local/bin/:/go/bin/darwin_amd64 golang \
  go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
docker run -e GOOS=darwin -e GOARCH=amd64 -v ~/usr/local/bin/:/go/bin/darwin_amd64 golang \
  go get github.com/brancz/gojsontoyaml
docker run -e GOOS=darwin -e GOARCH=amd64 -v ~/usr/local/bin/:/go/bin/darwin_amd64 golang \
  go get github.com/VirtusLab/render