#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"

echo_install "Installing passff"
curl -sSL https://github.com/passff/passff-host/releases/download/1.0.2/install_host_app.sh | bash -s -- firefox > /dev/null
print_in_green "${bold}✓ installed!${normal}\n"