#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"
assets="$(cd "$(dirname "$0")" && pwd)/../assets"

title "Shell"

mkdir -p "$HOME"/.landtech

echo_install "bins"
rm -Rf "$HOME"/.landtech/aliases
rm -Rf "$HOME"/.landtech/bin
cp -fr "$assets"/bin "$HOME"/.landtech/bin
print_in_green "${bold}✓ done!${normal}\n"

echo_install "aliases"
gopass show "${GOPASS_LANDTECH_STORE}"shell/aliases >"$HOME"/.landtech/aliases
print_in_green "${bold}✓ done!${normal}\n"
