#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"
assets="$(cd "$(dirname "$0")" && pwd)/../assets"

title "Shell"

mkdir -p "$HOME"/.landtech

echo_install "bins"
rm -Rf "$HOME"/.landtech/bin
cp -fr "$assets"/bin "$HOME"/.landtech/bin
print_in_green "${bold}✓ done!${normal}\n"
