#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"

title "Shell"

echo_install "assert.sh"
if curl --fail --retry 3 --retry-delay 1 -s -o /usr/local/bin/assert.sh https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh; then
    echo_install "assert.sh"
    print_in_green "${bold}✓ done!${normal}\n"
else
    print_error "assert.sh"
fi
