#!/usr/bin/env bash
source "$(pwd)/pretty-print"

# By default `bash` on MacOS is v3.x which is very old! The below upgrades you to the latest
# You'll end up with:
#   - /bin/bash <= v3.x
#   - /usr/local/bin/bash <= v5+
# /bin is a protected directly, it can't be changed (even with `sudo`), therefore on all scripts, at the top use:
# !/usr/bin/env bash
# https://itnext.io/upgrading-bash-on-macos-7138bd1066ba

title "Bash"

if ! brew list bash &> /dev/null; then
    echo_install "Installing bash"
    brew install bash > /dev/null
    brew link --overwrite bash
    print_in_green "${bold}✓ installed!${normal}\n"
else
    if ! brew outdated bash &>/dev/null; then
        echo_install "Upgrading bash"
        brew upgrade bash > /dev/null
        print_in_green "${bold}✓ upgraded!${normal}\n"
    else
        print_success_muted "bash"
    fi
fi
