#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"

# By default `bash` on MacOS is v3.x which is very old! The below upgrades you to the latest
# You'll end up with:
#   - /bin/bash <= v3.x
#   - /usr/local/bin/bash <= v5+
# /bin is a protected directly, it can't be changed (even with `sudo`), therefore on all scripts, at the top use:
# !/usr/bin/env bash
# https://itnext.io/upgrading-bash-on-macos-7138bd1066ba

brews=(
    # kubernetes
    aws-iam-authenticator
    jsonnet
    # password store
    gopass
    gnupg
    # bash testing
    bats
    expect
    # general
    bash
    git
    jq
    shellcheck
    tree
    wget
    watchman
    hub
    coreutils
)

title "Brews"

brew update > /dev/null
installed=$(brew list)
outdated=$(brew outdated)

for brew in "${brews[@]}"; do
    if ! echo "$installed" | grep -q $brew; then
        echo_install "Installing $brew"
		brew install $brew > /dev/null
        brew link --overwrite $brew &> /dev/null
		print_in_green "${bold}✓ installed!${normal}\n"
	else
        if [ "$FORCE" = true ]; then
            echo_install "Reinstalling $brew"
            brew reinstall "$brew" > /dev/null
		    print_in_green "${bold}✓ installed!${normal}\n"
        elif echo "$outdated" | grep -q "$brew"; then
            echo_install "Upgrading $brew"
            brew upgrade "$brew" > /dev/null
		    print_in_green "${bold}✓ upgraded!${normal}\n"
        else
            print_success_muted "$brew"
        fi
    fi
done

brew cleanup &> /dev/null