#!/usr/bin/env bash
source "$(pwd)/pretty-print"

casks=(
    docker
    firefox
    google-chrome
    gpg-suite
    iterm2
    postman
    robo-3t
    slack
    visual-studio-code
)

title "Casks"

for cask in "${casks[@]}"; do
    if ! brew cask list $cask &>/dev/null; then
        echo_install "Installing $cask"
        brew cask install $cask --appdir=/Applications >/dev/null
        print_in_green "${bold}✓ installed!${normal}\n"
    else
        if ! brew cask outdated "$cask" &>/dev/null; then
            echo_install "Upgrading $cask"
            brew cask upgrade "$cask" > /dev/null
		    print_in_green "${bold}✓ upgraded!${normal}\n"
        else
            print_success_muted "$cask"
        fi
    fi
done