#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"

casks=(
    docker
    firefox
    google-chrome
    gpg-suite
    iterm2
    slack
    visual-studio-code
)

title "Casks"
installed=$(brew list --cask)
outdated=$(brew outdated --cask)

for cask in "${casks[@]}"; do
    if ! echo "$installed" | grep -q "$cask"; then
        echo_install "Installing $cask"
        brew cask install "$cask" --appdir=/Applications >/dev/null
        print_in_green "${bold}✓ installed!${normal}\n"
    else
        if [ "$FORCE" = true ]; then
            echo_install "Reinstalling $cask"
            brew cask reinstall "$cask" >/dev/null
            print_in_green "${bold}✓ installed!${normal}\n"
        elif echo "$outdated" | grep -q "$cask"; then
            echo_install "Upgrading $cask"
            brew cask upgrade "$cask" >/dev/null
            print_in_green "${bold}✓ upgraded!${normal}\n"
        else
            print_success_muted "$cask"
        fi
    fi
done

# docker
if ! pgrep Docker >/dev/null; then
    echo_install "Starting docker"
    open /Applications/Docker.app
    sleep 25s
    print_in_green "${bold}✓ started!${normal}\n"
fi

echo_install "Cleaning docker"
docker system prune -f >/dev/null
print_in_green "${bold}✓ done!${normal}\n"

# casks outside of the reformation specified ones
other_casks=$(brew outdated --cask | wc -l)
if [ "$other_casks" -gt 0 ]; then
    print_warning "$other_casks other casks are outdated. Run 'brew upgrade --cask' to upgrade them."
fi
