#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"

casks=(
    docker
    firefox
    google-chrome
    gpg-suite
    iterm2
    postman
    robo-3t
    slack
    visual-studio-code
)

title "Casks"
installed=$(brew cask list)
outdated=$(brew cask outdated)

for cask in "${casks[@]}"; do
    if ! echo "$installed" | grep -q "$cask"; then
        echo_install "Installing $cask"
        brew cask install "$cask" --appdir=/Applications >/dev/null
        print_in_green "${bold}✓ installed!${normal}\n"
    else
        if [ "$FORCE" = true ]; then
            echo_install "Reinstalling $cask"
            brew cask reinstall "$cask" >/dev/null
            print_in_green "${bold}✓ installed!${normal}\n"
        elif echo "$outdated" | grep -q "$cask"; then
            echo_install "Upgrading $cask"
            brew cask upgrade "$cask" >/dev/null
            print_in_green "${bold}✓ upgraded!${normal}\n"
        else
            print_success_muted "$cask"
        fi
    fi
done

# start services
open /Applications/Docker.app
