#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"

modules=(
    eslint
	prettier
)

title "Node"

if ! brew list nvm &>/dev/null; then
	step "Installing NVM…"
	brew install nvm > /dev/null
	nvm install node &> /dev/null
	mkdir -p $HOME/.nvm
	print_success "nvm installed!"
else
	print_success_muted "nvm already installed. Skipping."
fi

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && source "/usr/local/opt/nvm/nvm.sh"
nvm use node > /dev/null

for module in "${modules[@]}"; do
	if ! npm list -g $module &> /dev/null; then
		echo_install "Installing $module"
		npm install $module -g --silent >/dev/null
		print_in_green "${bold}✓ installed!${normal}\n"
	else
		print_success_muted "$module"
		npm update $module -g --silent >/dev/null
	fi
done