#!/usr/bin/env bash
source "$CWD/pretty-print"

modules=(
	eslint
	prettier
)

title "Node"

export NVM_DIR="$HOME/.nvm"

if ! [ -x "$(command -v nvm)" ]; then
	step "Installing NVM…"
	curl -fsS https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

	nvm install node &>/dev/null
	print_success "nvm installed!"
else
	print_success_muted "nvm already installed. Skipping."
fi

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

for module in "${modules[@]}"; do
	if ! npm list -g $module &>/dev/null; then
		echo_install "Installing $module"
		npm install $module -g --silent >/dev/null
		print_in_green "${bold}✓ installed!${normal}\n"
	else
		print_success_muted "$module"
		npm update $module -g --silent >/dev/null
	fi
done
