#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"

packages=(
	pip
	credstash
	pipenv
	pylint
	pywatchman
)

title "Python"

if [ "$FORCE" = true ] || ! brew list python3 > /dev/null; then
	step "Installing Python…"
	brew install python3 > /dev/null
fi

for package in "${packages[@]}"; do
	pip3 install --upgrade --user $package --quiet
	print_success_muted "$package"
done
